# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: true
  branches:
    include:
      - integration

pool:
  vmImage: ubuntu-latest

- steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'
  # - task: npmAuthenticate@0
  #   inputs:
  #     workingFile: '.npmrc'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'version  1.0.$(build.buildid) --no-git-tag-version'
      customRegistry: 'useFeed'
      customFeed: 'b1cb2c79-6494-4aae-9934-2fc8f4c2046f/94a83a3b-7d49-45d7-8a5a-4edaaebb6c3f'

  - task: Npm@1
    inputs:
      command: 'install'
      verbose: true
      customRegistry: 'useFeed'
      customFeed: 'b1cb2c79-6494-4aae-9934-2fc8f4c2046f/94a83a3b-7d49-45d7-8a5a-4edaaebb6c3f'


  - task: Npm@1
    inputs:
      command: 'publish'
      verbose: true
      publishRegistry: 'useFeed'
      publishFeed: 'b1cb2c79-6494-4aae-9934-2fc8f4c2046f/94a83a3b-7d49-45d7-8a5a-4edaaebb6c3f'
