trigger: none

resources:
  pipelines:
  - pipeline: bt-app-stage-deploy # Name of the pipeline resource.
    source: bt-app-build # The name of the pipeline referenced by this pipeline resource.
    project: bootcamp-app # Required only if the source pipeline is in another project
    trigger:
      branches:
        - integration

variables:
- group: app-vars

stages: 
- stage:
  jobs:
  - deployment: deployApp
    displayName: Deploy App
    environment: stage
    strategy:                  
      runOnce:                 
        deploy:
          steps:       
          - template: template-deploy.yml
            parameters:
              servers: ['stage1', 'stage2', 'stage3']