trigger: none

resources:
  pipelines:
  - pipeline: bt-app-prod-deploy # Name of the pipeline resource.
    source: bt-app-stage-deploy # The name of the pipeline referenced by this pipeline resource.
    project: bootcamp-app # Required only if the source pipeline is in another project
    trigger:
      branches:
        - integration

variables:
- group: app-vars

stages: 
- stage:
  jobs:
  - template: template-deploy.yml
    parameters:
      servers: ['prod1', 'prod2', 'prod3']
      deployEnv: prod
